# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * Mon'  # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]
        platform: [x64]
        INSTALL_TYPE: [pip, conda]
        OPTIONAL_DEPS: [0, 1]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            OPTIONAL_DEPS: 1
            BUILD_DOCS: 1
            DEPLOY_DOCS: 1
            INSTALL_TYPE: pip
          - os: ubuntu-latest
            python-version: 3.8
            INSTALL_TYPE: pip
            OPTIONAL_DEPS: 1
            COVERAGE: 1
          - os: ubuntu-latest
            python-version: 3.8
            INSTALL_TYPE: pip
            OPTIONAL_DEPS: 1
            USE_PRE: 1
    env:
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }} # Keep backward compatibilty with Travis
      TRAVIS_REPO_SLUG: ${{ github.repository }}          # Keep backward compatibilty with Travis
      TRAVIS_BRANCH: ${{ github.head_ref }}               # Keep backward compatibilty with Travis
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}     # Keep backward compatibilty with Travis
      TRAVIS_BUILD_DIR: ${{ github.workspace }}           # Keep backward compatibilty with Travis
      ENV_DIR: ${HOME}/envs
      MESA_GL_VERSION_OVERRIDE: 3.3
      LIBGL_ALWAYS_INDIRECT: y
      DISPLAY: :99
      GH_REF: github.com/fury-gl/fury-website.git

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Environment variables
      run: |
        echo "[ "macos-latest" == "${{ matrix.os }}" ] && TRAVIS_OS_NAME="osx" || TRAVIS_OS_NAME="${{ matrix.os }}"" >> $GITHUB_ENV
        echo "[ "schedule" == "${{ github.event_name }}" ] && TRAVIS_EVENT_TYPE="cron" || TRAVIS_EVENT_TYPE="${{ github.event_name }}"" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        bash ci/travis/install.sh
    - name: Install and Test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          bash ci/travis/script.sh
    - name: Upload Coverage
      if: ${{ matrix.COVERAGE }} == 1
      run: |
          coveralls
          codecov
    - name: Deploy docs
      if: success()
      run: |
        bash ci/travis/deploy_docs.sh
